<a href="https://colab.research.google.com/github/ABChaeeun/ITB_Project/blob/main/%EC%9C%84%EB%8F%84%EA%B2%BD%EB%8F%84%EB%A5%BC_%EC%A3%BC%EC%86%8C%EB%A1%9C_%EC%B5%9C%EC%A2%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 위도, 경도를 동으로 바꾸기

In [12]:
# 좌표->주소 변환
from geopy.geocoders import Nominatim

def geocoding_reverse(lat_lng_str): 
    geolocoder = Nominatim(user_agent = 'South Korea', timeout=None)
    address = geolocoder.reverse(lat_lng_str)

    return address


def print_dong(lat_long):
  address = geocoding_reverse(lat_long)
  for i in address[0].split(','):
    if i[-1] == '동':
      return i

### 데이터에 적용

In [2]:
import pandas as pd

In [3]:
rental_shop_data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/<it와비즈니스혁신>/과제 #3. 기말프로젝트/따릉이_용산구_대여소.xlsx")
rental_shop_data

,대여소\n번호,보관소(대여소)명,자치구,소재지(위치),위도,경도,설치\n시기,거치대수,운영\n방식
0,800,목월공원 앞,용산구,서울특별시 용산구 원효로4가 109-10,37.532433,126.954742,2016-06-29,15.0,LCD
1,802,한강진역 2번 출구 앞,용산구,서울특별시 용산구 한남동 726-494,37.541153,127.002212,2016-06-29,10.0,LCD
2,803,한남초교 앞 보도육교,용산구,서울특별시 용산구 한남동 725-17,37.538139,127.004097,2016-06-29,10.0,LCD
3,805,문배어린이공원 앞,용산구,서울특별시 용산구 문배동 34-10,37.536758,126.970001,2016-06-29,9.0,LCD
4,806,전자랜드 본관 앞,용산구,서울특별시 용산구 한강로3가 16-8,37.533066,126.960731,2016-06-29,15.0,LCD
...,...,...,...,...,...,...,...,...,...
83,4634,이태원역 3번 출구,용산구,이태원동 119-23,37.534401,126.994667,NaT,NaN,QR
84,4636,용산구꿈나무종합타운 앞,용산구,용산구 원효로2가 1-22,37.537861,126.965653,2022-06-08,8.0,QR
85,4637,용산시티파크 101동 앞,용산구,서빙고로 35,37.524681,126.968193,2022-06-09,10.0,QR
86,4638,청파동삼거리 앞,용산구,청파동1가 180-33,37.547337,126.970383,2022-06-09,10.0,QR
87,4639,동빙고근린공원,용산구,용산동6가 69-170,37.517941,126.983704,2022-06-09,10.0,QR

In [ ]:
rental_shop_data['동'] = None

In [ ]:
for x in range(len(rental_shop_data['소재지(위치)'])):
  print(x)
  strr = str(rental_shop_data['위도'][x]), str(rental_shop_data['경도'][x])
  # print_dong(strr)
  rental_shop_data['동'][x] = print_dong(strr)

0

<ipython-input-108-19d3c97205e5>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_shop_data['동'][x] = print_dong(strr)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87

In [ ]:
rental_shop_data

,대여소\n번호,보관소(대여소)명,자치구,소재지(위치),위도,경도,설치\n시기,거치대수,운영\n방식,동
0,800,목월공원 앞,용산구,서울특별시 용산구 원효로4가 109-10,37.532433,126.954742,2016-06-29,15.0,LCD,원효로1동
1,802,한강진역 2번 출구 앞,용산구,서울특별시 용산구 한남동 726-494,37.541153,127.002212,2016-06-29,10.0,LCD,한남동
2,803,한남초교 앞 보도육교,용산구,서울특별시 용산구 한남동 725-17,37.538139,127.004097,2016-06-29,10.0,LCD,한남동
3,805,문배어린이공원 앞,용산구,서울특별시 용산구 문배동 34-10,37.536758,126.970001,2016-06-29,9.0,LCD,원효로1동
4,806,전자랜드 본관 앞,용산구,서울특별시 용산구 한강로3가 16-8,37.533066,126.960731,2016-06-29,15.0,LCD,한강로동
...,...,...,...,...,...,...,...,...,...,...
83,4634,이태원역 3번 출구,용산구,이태원동 119-23,37.534401,126.994667,NaT,NaN,QR,이태원1동
84,4636,용산구꿈나무종합타운 앞,용산구,용산구 원효로2가 1-22,37.537861,126.965653,2022-06-08,8.0,QR,원효로1동
85,4637,용산시티파크 101동 앞,용산구,서빙고로 35,37.524681,126.968193,2022-06-09,10.0,QR,한강로동
86,4638,청파동삼거리 앞,용산구,청파동1가 180-33,37.547337,126.970383,2022-06-09,10.0,QR,청파동
87,4639,동빙고근린공원,용산구,용산동6가 69-170,37.517941,126.983704,2022-06-09,10.0,QR,서빙고동

In [ ]:
rental_shop_data.to_excel('rental_shop_dong_data.xlsx')

In [ ]:
address = geocoding_reverse('37.53442383, 126.9485703')
address[0].split(',')

['강변삼성아파트 102동', ' 원효로', ' 원효로1동', ' 용산구', ' 서울', ' 04365', ' 대한민국']

In [ ]:
address = geocoding_reverse('37.53269958, 126.9643784')
address[0].split(',')

['선인상가 21동', ' 새창로', ' 한강로동', ' 용산구', ' 서울', ' 04377', ' 대한민국']